name: ptensors
channels:
  - defaults
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - pip==24.0
  - conda-forge::lightning==2.2.2
  - conda-forge::ogb==1.3.6
  - pyg::pyg
  - python=3.10
  - pytorch::pytorch-cuda=11.7
  - pytorch-scatter
  - pytorch::pytorch==2.0.1
  - pytorch::torchaudio==2.0.2
  - pytorch::torchvision==0.15.2
  - wandb==0.16.5
  - pip:
    - pytorch-optimizer==2.12.0