program: main.py
name: zinc-subset
method: grid
metric:
  goal: minimize
  name: val_score
parameters:
  dataset:
    value: "peptides-struct"
  mode:
    value: "min"
  eval_metric:
    value: "MAE"
  loss:
    value: "BCEWithLogits"
  lr:
    values: [0.001]
  min_lr:
    values: [1.0E-5]
  batch_size:
    value: 256
  seed:
    values: [1]
  bn_momentum:
    values: [0.1]
  num_epochs:
    value: 1000
  optimizer:
    value: "adam"
  lr_scheduler:
    value: "ReduceLROnPlateau"
  patience:
    value: 60
  hidden_channels:
    values: [64]
  feature_encoder:
    value: "OGB"