program: src/main.py
name: peptides-struct
method: grid
metric:
  goal: minimize
  name: val_score
parameters:
  dataset:
    value: "peptides-struct"
  mode:
    value: "min"
  eval_metric:
    value: "MAE"
  loss:
    value: "MAE"
  lr:
    values: [0.001]
  min_lr:
    values: [1.0E-5]
  num_layers:
    value: 4
  batch_size:
    values: [128]
  seed:
    values: [1,2,3,4,5,6,7,8,9,10]
  bn_momentum:
    values: [0.1]
  num_epochs:
    value: 350
  optimizer:
    value: "adam"
  lr_scheduler:
    value: "ReduceLROnPlateau"
  patience:
    values: [60]
  dropout:
    values: [0.1]
  hidden_channels:
    values: [64]
  feature_encoder:
    value: "OGB"
  enable_model_summary:
    value: True