program: main_simple.py
name: zinc-subset
method: grid
metric:
  goal: minimize
  name: val_score
parameters:
  dataset:
    value: "ZINC"
  mode:
    value: "min"
  eval_metric:
    value: "MAE"
  loss:
    value: "MAE"
  lr:
    values: [0.001]
  min_lr:
    values: [1.0E-5]
  batch_size:
    value: 256
  seed: 
    values: [1,2,3,4,5,6,7,8,9,10]
  bn_momentum:
    values: [0.1]
  num_epochs:
    value: 2000
  task_type:
    value: "single-target-regression"
  optimizer: 
    value: "adam"
  lr_scheduler:
    value: "ReduceLROnPlateau"
  patience:
    value: 40
  hidden_channels: 
    values: [128]
  feature_encoder:
    value: "Embedding"